
site_name: DHCP
theme:
  name: material
nav:
  - Inici: index.md
  - Objectius: objectius.md
  - Continguts: continguts.md
  - Seccions:
    - 1. Introducció: 1_introducci.md
    - 2. Configuració dels equips de la xarxa: 2_configuraci_dels_equips_de_la_xarxa.md
    - 3. El model funcional DHCP: 3_el_model_funcional_dhcp.md
    - 4. Intervals, exclusions, concessions i reserves: 4_intervals_exclusions_concessions_i_reserves.md
    - 5. Opcions addicionals del protocol: 5__opcions_addicionals_del_protocol.md
    - 6. Problemes del servei: 6_problemes_del_servei.md
  - Instal·lació d'un servidor DHCP: installaci_dun_servidor__dhcp.md
  - Activitats: activitats.md
  - Pràctiques: prctiques.md
